import { TaskItems } from "./Task.ts";

export const links: TaskItems[] = [
  {
    id: 1,
    title: "Complete React project",
    description: "Finish the React project for dynamic pagination.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 2,
    title: "Write project documentation",
    description: "Document the project setup and implementation details.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 3,
    title: "Fix pagination bug",
    description: "Resolve issue with duplicate tasks on scroll.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 4,
    title: "Update API endpoint",
    description: "Update the task fetching API to support filtering by status.",
    priority: "Low",
    status: "Not Completed",
  },
  {
    id: 5,
    title: "Optimize task loading",
    description: "Implement caching for previously loaded pages.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 6,
    title: "Design UI for task manager",
    description: "Create a modern and responsive design for the task manager interface.",
    priority: "High",
    status: "Completed",
  },
  {
    id: 7,
    title: "Conduct code review",
    description: "Review the codebase to ensure best practices are followed.",
    priority: "Medium",
    status: "Completed",
  },
  {
    id: 8,
    title: "Write unit tests",
    description: "Add unit tests for critical components in the app.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 9,
    title: "Deploy application",
    description: "Deploy the task manager app to a hosting service.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 10,
    title: "User feedback",
    description: "Gather feedback from initial users and make improvements.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 11,
    title: "Fix UI bugs",
    description: "Resolve alignment and responsiveness issues.",
    priority: "Low",
    status: "Completed",
  },
  {
    id: 12,
    title: "Update dependencies",
    description: "Ensure all npm packages are up to date.",
    priority: "Medium",
    status: "Completed",
  },
  {
    id: 13,
    title: "Create API documentation",
    description: "Document the API endpoints and expected responses.",
    priority: "Low",
    status: "Not Completed",
  },
  {
    id: 14,
    title: "Implement search feature",
    description: "Allow users to search for specific tasks by title or description.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 15,
    title: "Add filter options",
    description: "Enable filtering tasks by priority or status.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 16,
    title: "Improve error handling",
    description: "Handle network errors gracefully with user-friendly messages.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 17,
    title: "Update footer design",
    description: "Add useful links and improve the layout of the footer.",
    priority: "Low",
    status: "Completed",
  },
  {
    id: 18,
    title: "Conduct usability testing",
    description: "Test the app with real users to identify usability issues.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 19,
    title: "Create demo video",
    description: "Produce a video demonstrating the app's features.",
    priority: "Low",
    status: "Completed",
  },
  {
    id: 20,
    title: "Research competitors",
    description: "Analyze similar task management apps to find unique features.",
    priority: "Low",
    status: "Not Completed",
  },
  {
    id: 21,
    title: "Fix accessibility issues",
    description: "Ensure the app is usable for users with disabilities.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 22,
    title: "Set up CI/CD pipeline",
    description: "Automate testing and deployment processes.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 23,
    title: "Refactor codebase",
    description: "Simplify and optimize the code structure.",
    priority: "Medium",
    status: "Completed",
  },
  {
    id: 24,
    title: "Implement dark mode",
    description: "Add an option for users to switch to a dark theme.",
    priority: "Low",
    status: "Not Completed",
  },
  {
    id: 25,
    title: "Add notifications",
    description: "Notify users of task deadlines and updates.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 26,
    title: "Localize app",
    description: "Support multiple languages for a broader audience.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 27,
    title: "Integrate calendar",
    description: "Allow users to view tasks on a calendar view.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 28,
    title: "Improve onboarding",
    description: "Make it easier for new users to understand the app.",
    priority: "Low",
    status: "Completed",
  },
  {
    id: 29,
    title: "Update logo",
    description: "Design a new logo that reflects the app's purpose.",
    priority: "Low",
    status: "Completed",
  },
  {
    id: 30,
    title: "Add export feature",
    description: "Allow users to export their tasks to a file.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 31,
    title: "Fix backend API bugs",
    description: "Resolve issues causing delays in task fetching.",
    priority: "High",
    status: "Completed",
  },
  {
    id: 32,
    title: "Optimize database queries",
    description: "Improve performance of task-related database operations.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 33,
    title: "Add priority icons",
    description: "Display icons next to tasks to indicate their priority.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 34,
    title: "Create FAQ section",
    description: "Provide answers to common user questions.",
    priority: "Low",
    status: "Completed",
  },
  {
    id: 35,
    title: "Add task history",
    description: "Allow users to view changes made to tasks over time.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 36,
    title: "Implement drag-and-drop",
    description: "Enable reordering of tasks via drag-and-drop.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 37,
    title: "Fix mobile layout issues",
    description: "Ensure the app is fully responsive on mobile devices.",
    priority: "Medium",
    status: "Completed",
  },
  {
    id: 38,
    title: "Add task reminders",
    description: "Notify users of upcoming deadlines.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 39,
    title: "Integrate with Google Calendar",
    description: "Allow users to sync tasks with their Google Calendar.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 40,
    title: "Update task icons",
    description: "Modernize the icons used in the task list.",
    priority: "Low",
    status: "Completed",
  },
  {
    id: 41,
    title: "Enhance security",
    description: "Ensure user data is securely stored and transmitted.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 42,
    title: "Improve loading speed",
    description: "Optimize images and scripts to reduce page load time.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 43,
    title: "Implement offline mode",
    description: "Allow users to manage tasks without an internet connection.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 44,
    title: "Add color themes",
    description: "Provide users with customizable color themes.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 45,
    title: "Add task comments",
    description: "Allow users to add notes or comments to tasks.",
    priority: "Medium",
    status: "Not Completed",
  },
  {
    id: 46,
    title: "Integrate analytics",
    description: "Track user interactions to improve the app.",
    priority: "Low",
    status: "Not Completed",
  },
  {
    id: 47,
    title: "Add bulk edit feature",
    description: "Allow users to edit multiple tasks at once.",
    priority: "High",
    status: "Not Completed",
  },
  {
    id: 48,
    title: "Improve navigation",
    description: "Simplify navigation for better user experience.",
    priority: "Low",
    status: "Completed",
  },
  {
    id: 49,
    title: "Add feedback form",
    description: "Enable users to submit their feedback directly through the app.",
    priority: "Low",
    status: "Completed",
  },
  {
    id: 50,
    title: "Fix search issues",
    description: "Resolve inconsistencies in the search results.",
    priority: "High",
    status: "Not Completed",
  },
];
